### ISSUE TITLE
Incorrent Semver for ink-4 peerDependency

### ISSUE THREAD

**Issue by jackhatton** [lukasbach/ink-form#10]
When running npm install ink-form while in an Ink 4 project, the peerDependency fails to resolve.

Steps to Replicate:
`npx create-ink-app --typescript`
`npm i ink-form`

I expected the library to install without issue as of #8, Ink 4 support issue had been closed.

![Screenshot 2024-05-09 at 6 50 03 PM](https://github.com/lukasbach/ink-form/assets/84044652/590dae12-d8c1-481a-a1a7-cee09876f7b8)

Link to line causing problem:
https://github.com/lukasbach/ink-form/blob/70ab43446fe4126b3a63b8970317c43046528eb2/package.json#L48

**Comment by torickjdavis** [comment]
Using the [NPM semver calculator](https://semver.npmjs.com/), it can be seen that `>4` results in no matches, while `^4` would include everything from `4.0.0` and beyond.

**Comment by lukasbach** [comment]
Thanks for noticing, the the PR. The issue with `^` is that it also just limits it to the specific major version, which isn't necessarily required in each case, for example ink-form works fine with both ink 4 and ink 5. I've updated the range to `>=4` which should now be correct.
