### ISSUE TITLE
Custom form field types are currently not possible due to incorrect types.d.ts in the distribution

### ISSUE THREAD

**Issue by cyoclay** [lukasbach/ink-form#5]
The declaration of FormField in types.d.ts is the below:

`export declare type FormField = FormFieldString | FormFieldInteger | FormFieldFloat | FormFieldSelect | FormFieldMultiSelect | FormFieldBoolean;`

From reading the source code, I expected it to contain `AbstractFormField<any, any>` as one of the unioned types, like this: 

`export declare type FormField = FormFieldString | FormFieldInteger | FormFieldFloat | FormFieldSelect | FormFieldMultiSelect | FormFieldBoolean | AbstractFormField<any, any>;`

This prevents any custom form field types from being declared; all custom form field manager declarations display the error
```
TS2344: Type 'FormFieldCustom' does not satisfy the constraint 'FormField'.   
Type 'FormFieldCustom' is not assignable to type 'AbstractFormField<"boolean", boolean>'.     
Types of property 'type' are incompatible.       
Type '"custom"' is not assignable to type '"boolean"'.
```

I have the latest distribution installed, 1.0.1.

**Comment by lukasbach** [comment]
I published a new version where this should be fixed.
