### ISSUE TITLE
Is there a way to display a conditional form input based on another input's value?

### ISSUE THREAD

**Issue by dcominottim** [lukasbach/ink-form#6]
Hi! Kudos for the great project. 

I am considering the use of ink-form in a CLI app but I need to be able to conditionally display some inputs (e.g.: a text input) based on the value of others (e.g.: in a "Yes"/"No" input, "Yes" was selected).

Is there a way to do it or any plan to add it in the near future? Thanks a lot!

**Comment by lukasbach** [comment]
Hi @dcominottim, you could try to implement the form as [React component](https://github.com/lukasbach/ink-form/blob/main/src/demo/custommanager.tsx), register value change listeners (see [AbstractFormField:onChange](https://lukasbach.github.io/ink-form/modules.html#abstractformfield)) for whatever should trigger to decide whether to show certain inputs or not, and have them render conditionally on those values.
